pdf:
    storage:
        path: /data/generated_pdfs
    cleanup:
        file-retention-duration-ms: 1800000  # Time files are retained before deletion (30 minutes in milliseconds)
        cleanup-interval-ms: 600000          # Frequency of cleanup checks (10 minutes in milliseconds)
    ranking:
        root: "https://comercial.central.inditex.grp/cdarkspa-st4/web/export"
        domain: "comercial.central.inditex.grp"
        environment: "local"
        articles-per-pdf: 200
        batch-size: 2
    executor:
        pool-size: 1
    pages-to-remove: 2

cors:
    allowed-origin: "https://comercial.central.inditex.grp"

server:
    port: 8080

spring:
    application:
        name: pdfgenerator