pdf:
    storage:
        path: /data/generated_pdfs
    cleanup:
        retention-minutes: 30
        interval-minutes: 10
    ranking:
        root: "https://comercial.central.inditex.grp/cdarkspa-st4/web/export"
        domain: "comercial.central.inditex.grp"
        environment: "local"
        articles-per-pdf: 200
        batch-size: 2
    executor:
        pool-size: 1

cors:
    allowed-origin: "https://comercial.central.inditex.grp"

server:
    port: 8080

spring:
    application:
        name: pdfgenerator